version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
        - "Cyb3r-Jak3"
    labels:
        - "dependencies"
    reviewers:
        - "Cyb3r-Jak3"
    