stages:
    - build
    - test

include:
  - template: Container-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml


.docker_build:
    stage: build
    image: docker:19.03.12
    services:
        - docker:19.03.12-dind


Main-Test:
    extends: .docker_build
    script:
        - docker build --file Dockerfiles/pypi/alpine.Dockerfile --tag html5validator:latest .
        - docker run --rm -i -v $(pwd)/tests:/tests/ html5validator:latest html5validator --root /tests/ --log DEBUG

GitLab-Scanning:
    extends: .docker_build
    variables:
        IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    before_script:
        - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    script:
        - docker build --tag $IMAGE --file Dockerfiles/pypi/alpine.Dockerfile  .
        - docker push $IMAGE
