stages:
    - build
docker_build:
    stage: build
    image: docker:19.03.0-dind
    services:
        - name: docker:dind
          entrypoint: ["env", "-u", "DOCKER_HOST"]
          command: ["dockerd-entrypoint.sh"]
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        # See https://github.com/docker-library/docker/pull/166
        DOCKER_TLS_CERTDIR: ""
    script:
        - docker build --file Dockerfiles/PyPi/PyPi-alpine.DockerFile --tag html5validator:latest --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .
        - docker run --rm -i -v $(pwd)/tests:/tests/ html5validator:latest --root /tests/valid --log DEBUG
  