name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

jobs:
  build_self:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Self Docker
      run: docker build . --file Dockerfile-Self --tag cyb3rjak3/html5validator:self
  build_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Self Docker
      run: docker build . --file Dockerfile-PyPi --tag cyb3rjak3/html5validator:pypi
  publish_self:
    needs: build_self
    runs-on: ubuntu-latest
    steps:
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: cyb3rjak3/html5validator
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: DockerFile-Self
        snapshot: true
  publish_pypi:
    needs: build_pypi
    runs-on: ubuntu-latest
    steps:
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: cyb3rjak3/html5validator
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: DockerFile-PyPi
        snapshot: true
