name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jwhite1st:html5validator-$(GITHUB_REF)-$(date +%s)
  publish:
  - name: Publish Docker
  uses: elgohr/Publish-Docker-Github-Action@2.7

