name: GitHub CI
on:
  push:
    branches:
      - develop
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

jobs:
  Build_Source:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Source
      run: |
        docker login docker.pkg.github.com --username cyb3r-jak3  -p ${{ secrets.GITHUB_TOKEN }}
        #docker pull docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator:source  --cache-from docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-source:source
        docker build --file DockerFile-Source --tag docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-source:latest .
        docker push docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-source:latest

  Build_Pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build PyPi
      run: |
        docker login docker.pkg.github.com --username cyb3r-jak3  -p ${{ secrets.GITHUB_TOKEN }}
        #docker pull docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator:pypi --cache-from docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator:pypi
        docker build --file DockerFile-PyPi --tag docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-pypi:latest .
        docker push docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-pypi:latest