name: GitHub CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * 0'

jobs:
  Source:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Source For GitHub
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username cyb3r-jak3  --password-stdin
    - name: Build Source For GitHub
      run: |
        docker build --file Source.DockerFile --tag docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-source:latest --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .
        docker build --file Source-alpine.DockerFile --tag docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-source:latest-alpine --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .
    - name: Push Source For GitHub
      run: docker push docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-source:latest; docker push docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-source:latest-alpine

  Pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PyPi For GitHub
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username cyb3r-jak3  --password-stdin
    - name: Build PyPi For GitHub
      run: |
        docker build --file PyPi.DockerFile --tag docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-pypi:latest --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .
        docker build --file PyPi-alpine.DockerFile --tag docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-pypi:latest-alpine --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .
    - name: Push PyPi to GitHub
      run: docker push docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-pypi:latest; docker push docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-pypi:latest-alpine

  Experimental:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Experimental For GitHub
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username cyb3r-jak3  --password-stdin
    - name: Build Experimental For GitHub
      run: |
        docker build --file Experimental.DockerFile --tag docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-experimental:latest --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .
        docker build --file Experimental-alpine.DockerFile --tag docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-experimental:latest-alpine --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .
    - name: Push Experimental to GitHub
      run: docker push docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-experimental:latest; docker push docker.pkg.github.com/cyb3r-jak3/html5validator-docker/html5validator-experimental:latest-alpine