name: Check Merge

on:
  pull_request:
    branches:
      - master
  
jobs:
    Source:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.3.4
        - name: Setup ENV
          run: |
            echo "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" >> $GITHUB_ENV
            echo "VCS_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1.1.0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1.3.0

        - name: Cache Docker layers
          uses: actions/cache@v2.1.5
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}
        
        - name: Build and push
          uses: docker/build-push-action@v2.5.0
          with:
            platforms: linux/amd64,linux/arm64,linux/arm
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            push: false
            file: Dockerfiles/Source/Source.DockerFile
            tags: cyb3rjak3/html5validator:source
            build-args: |
              BUILD_DATE=${BUILD_DATE}
              VCS_REF=${VCS_REF}

        - name: Run Source Docker
          run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:source html5validator --root /tests/valid --log DEBUG

    Source-Alpine:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.3.4
        - name: Setup ENV
          run: |
            echo "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" >> $GITHUB_ENV
            echo "VCS_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1.1.0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1.3.0

        - name: Cache Docker layers
          uses: actions/cache@v2.1.5
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}
        
        - name: Build and push
          uses: docker/build-push-action@v2.5.0
          with:
            platforms: linux/amd64,linux/arm64,linux/arm
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            push: false
            file: Dockerfiles/Source/Source-alpine.DockerFile
            tags: cyb3rjak3/html5validator:source-alpine
            build-args: |
              BUILD_DATE=${BUILD_DATE}
              VCS_REF=${VCS_REF}

        - name: Run Source-Alpine Docker
          run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:source-alpine html5validator --root /tests/valid --log DEBUG

    Pypi:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.3.4
        - name: Setup ENV
          run: |
            echo "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" >> $GITHUB_ENV
            echo "VCS_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1.1.0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1.3.0

        - name: Cache Docker layers
          uses: actions/cache@v2.1.5
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}
        
        - name: Build and push
          uses: docker/build-push-action@v2.5.0
          with:
            platforms: linux/amd64,linux/arm64,linux/arm
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            push: false
            file: Dockerfiles/PyPi/PyPi.DockerFile
            tags: |
              cyb3rjak3/html5validator:pypi
              cyb3rjak3/html5validator:latest
            build-args: |
              BUILD_DATE=${BUILD_DATE}
              VCS_REF=${VCS_REF}
        - name: Run PyPi Docker
          run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:latest html5validator --root /tests/valid --log DEBUG
    
    Pypi-Alpine:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.3.4
        - name: Setup ENV
          run: |
            echo "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" >> $GITHUB_ENV
            echo "VCS_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1.1.0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1.3.0

        - name: Cache Docker layers
          uses: actions/cache@v2.1.5
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}
        
        - name: Build and push
          uses: docker/build-push-action@v2.5.0
          with:
            platforms: linux/amd64,linux/arm64,linux/arm
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            push: false
            file: Dockerfiles/PyPi/PyPi-alpine.DockerFile
            tags: |
              cyb3rjak3/html5validator:pypi-alpine
              cyb3rjak3/html5validator:latest-alpine
            build-args: |
              BUILD_DATE=${BUILD_DATE}
              VCS_REF=${VCS_REF}
        - name: Run PyPi-Alpine Docker
          run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:latest-alpine html5validator --root /tests/valid --log DEBUG

    Experimental:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.3.4
        - name: Setup ENV
          run: |
            echo "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" >> $GITHUB_ENV
            echo "VCS_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1.1.0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1.3.0

        - name: Cache Docker layers
          uses: actions/cache@v2.1.5
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}
        
        - name: Build and push
          uses: docker/build-push-action@v2.5.0
          with:
            platforms: linux/amd64,linux/arm64,linux/arm
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            push: false
            file: Dockerfiles/Experimental/Experimental.DockerFile
            tags: cyb3rjak3/html5validator:experimental
            build-args: |
              BUILD_DATE=${BUILD_DATE}
              VCS_REF=${VCS_REF}
        - name: Run Experimental Docker
          run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:experimental html5validator --root /tests/valid --log DEBUG

    Experimental-Alpine:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.3.4
        - name: Setup ENV
          run: |
            echo "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" >> $GITHUB_ENV
            echo "VCS_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1.1.0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1.3.0

        - name: Cache Docker layers
          uses: actions/cache@v2.1.5
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-${{ env.GITHUB_WORKFLOW }}
        
        - name: Build and push
          uses: docker/build-push-action@v2.5.0
          with:
            platforms: linux/amd64,linux/arm64,linux/arm
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            push: false
            file: Dockerfiles/Experimental/Experimental-alpine.DockerFile
            tags: cyb3rjak3/html5validator:experimental-alpine
            build-args: |
              BUILD_DATE=${BUILD_DATE}
              VCS_REF=${VCS_REF}
        - name: Run Experimental-Alpine Docker
          run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:experimental-alpine html5validator --root /tests/valid --log DEBUG
