name: Publish

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfiles/**'
      - '.github/workflows/publish.yml'
      - 'docker-bake.hcl'
    tags:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write      

jobs:
  Publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: ["source", "pypi"]
        buildArch: ["slim", "alpine"]
    steps:

      - name: Login to Docker
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login To GitHub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login To GitLab
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USER }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          flavor: |
            latest=false
          images: cyb3rjak3/html5validator,ghcr.io/cyb3r-jak3/html5validator,registry.gitlab.com/cyb3r-jak3/html5validator-docker
          labels: |
            org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/html5validator-docker.git
            maintainer=Cyb3r Jak3 git@cyberjake.xyz
            org.opencontainers.image.vendor=cyb3rjak3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build
        uses: docker/bake-action@3acf805d94d93a86cce4ca44798a76464a75b88c # v6.9.0
        with:
          source: .
          files: |
            ${{ steps.meta.outputs.bake-file }}
            ./docker-bake.hcl
          targets: ${{matrix.buildType}}-${{matrix.buildArch}}-release
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          sbom: true
          provenance: true
          set: |
            *.cache-from=type=gha,scope=buildx-${{matrix.buildType}}-${{matrix.buildArch}}
            *.cache-to=type=gha,mode=max,scope=buildx-${{matrix.buildType}}-${{matrix.buildArch}}
        env:
          DOCKER_META_VERSION: ${{ env.DOCKER_METADATA_OUTPUT_VERSION }}
