name: Publish Source Images

on:
  push:
    branches:
      - master
    paths:
      - Dockerfiles/Source/**
      - .github/workflows/publish_source.yml
    tags:
      - "v*"
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 1 * * 0'

jobs:
    Build_Push:
        runs-on: ubuntu-latest
        steps:

        - name: Login to Docker
          uses: docker/login-action@v1
          if: ${{ startsWith(github.ref, 'refs/tags/v') }}
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Login To GitHub
          uses: docker/login-action@v1
          if: ${{ startsWith(github.ref, 'refs/tags/v') }}
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.CR_PAT }}

        - name: Login To GitLab
          uses: docker/login-action@v1
          if: ${{ startsWith(github.ref, 'refs/tags/v') }}
          with:
            registry: registry.gitlab.com
            username: ${{ secrets.GITLAB_USER }}
            password: ${{ secrets.GITLAB_TOKEN }}

        - name: Docker Meta
          id: meta
          uses: docker/metadata-action@v3
          with:
            images: cyb3rjak3/html5validator,ghcr.io/cyb3r-jak3/html5validator,registry.gitlab.com/cyb3r-jak3/html5validator-docker
            labels: |
              org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/html5validator-docker.git
              maintainer=Cyb3r Jak3 jake@jwhite.network

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1.2.0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1.3.0

        - name: Cache Docker layers
          uses: actions/cache@v2.1.5
          with:
            path: /tmp/.buildx-cache
            key: buildx-source-${{ github.sha }}
            restore-keys: buildx-source
        
        - name: Source Slim
          uses: docker/build-push-action@v2.5.0
          with:
            platforms: linux/amd64,linux/arm64,linux/arm
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            push: ${{ startsWith(github.ref, 'refs/tags/v') }}
            file: Dockerfiles/Source/Source.DockerFile
            labels: ${{ steps.meta.outputs.labels }}
            tags: |
              cyb3rjak3/html5validator:source-slim
              ghcr.io/cyb3r-jak3/html5validator:source-slim
              registry.gitlab.com/cyb3r-jak3/html5validator-docker:source-slim

        - name: Source Alpine
          uses: docker/build-push-action@v2.5.0
          with:
            platforms: linux/amd64,linux/arm64,linux/arm
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            push: ${{ startsWith(github.ref, 'refs/tags/v') }}
            file: Dockerfiles/Source/Source-alpine.DockerFile
            labels: ${{ steps.meta.outputs.labels }}
            tags: |
              cyb3rjak3/html5validator:source-alpine
              cyb3rjak3/html5validator:source
              ghcr.io/cyb3r-jak3/html5validator:source
              ghcr.io/cyb3r-jak3/html5validator:source-alpine
              registry.gitlab.com/cyb3r-jak3/html5validator-docker:source
              registry.gitlab.com/cyb3r-jak3/html5validator-docker:source-alpine

        - uses: actions/checkout@v2.3.4

        - name: Run Source-Slim Docker
          run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:source-slim html5validator --root /tests/valid --log DEBUG

        - name: Run Source-Alpine Docker
          run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:source-alpine html5validator --root /tests/valid --log DEBUG