name: Publish Pypi Images

on:
  push:
    branches:
      - master
    tags:
      - "v*"
    paths:
      - Dockerfiles/PyPi/**
      - .github/workflows/publish_pypi.yml
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 1 * * 0'

jobs:
    Build_Push:
      runs-on: ubuntu-latest
      steps:

      - name: Login to Docker
        uses: docker/login-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login To GitHub
        uses: docker/login-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Login To GitLab
        uses: docker/login-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USER }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: cyb3rjak3/html5validator,ghcr.io/cyb3r-jak3/html5validator,registry.gitlab.com/cyb3r-jak3/html5validator-docker
          labels: |
            org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/html5validator-docker.git
            maintainer=Cyb3r Jak3 jake@jwhite.network

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Cache Docker layers
        uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: buildx-pypi-${{ github.sha }}
          restore-keys: buildx-pypi

      - name: Pypi Slim
        uses: docker/build-push-action@v2.5.0
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          file: Dockerfiles/PyPi/PyPi.DockerFile
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/cyb3r-jak3/html5validator:latest-slim
            ghcr.io/cyb3r-jak3/html5validator:pypi-slim
            cyb3rjak3/html5validator:pypi-slim
            cyb3rjak3/html5validator:latest-slim
            registry.gitlab.com/cyb3r-jak3/html5validator-docker:pypi-slim
            registry.gitlab.com/cyb3r-jak3/html5validator-docker:latest-slim


      - name: Pypi Alpine
        uses: docker/build-push-action@v2.5.0
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          file: Dockerfiles/PyPi/PyPi-alpine.DockerFile
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            cyb3rjak3/html5validator:pypi-alpine
            cyb3rjak3/html5validator:pypi
            cyb3rjak3/html5validator:latest-alpine
            cyb3rjak3/html5validator:latest
            ghcr.io/cyb3r-jak3/html5validator:latest-alpine
            ghcr.io/cyb3r-jak3/html5validator:latest
            ghcr.io/cyb3r-jak3/html5validator:pypi
            ghcr.io/cyb3r-jak3/html5validator:pypi-alpine
            registry.gitlab.com/cyb3r-jak3/html5validator-docker:pypi-alpine
            registry.gitlab.com/cyb3r-jak3/html5validator-docker:pypi
            registry.gitlab.com/cyb3r-jak3/html5validator-docker:latest-alpine
            registry.gitlab.com/cyb3r-jak3/html5validator-docker:latest
