name: Publish Source Images

on:
  push:
    branches:
      - master
    paths:
      - Dockerfiles/Source/**
  schedule:
    - cron: '0 1 * * 0'

jobs:
    Build_Push:
        runs-on: ubuntu-latest
        steps:

        - name: Login To GitHub
          run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

        - name: Login To GitLab
          run: echo ${{ secrets.GITLAB_TOKEN }} | docker login registry.gitlab.com -u ${{ secrets.GITLAB_USER }} --password-stdin

        - name: Login to Docker
          run: echo ${{ secrets.DOCKER_PASSWORD }} |  docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

        - uses: actions/checkout@v2.3.4
        - name: Setup ENV
          run: |
            echo "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" >> $GITHUB_ENV
            echo "VCS_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1.1.0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1.3.0

        - name: Cache Docker layers
          uses: actions/cache@v2.1.5
          with:
            path: /tmp/.buildx-cache
            key: buildx-source-${{ github.sha }}
            restore-keys: buildx-source
        
        - name: Source Slim
          uses: docker/build-push-action@v2.5.0
          with:
            platforms: linux/amd64,linux/arm64,linux/arm
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            push: true
            file: Dockerfiles/Source/Source.DockerFile
            tags: |
              cyb3rjak3/html5validator:source-slim
              ghcr.io/cyb3r-jak3/html5validator:source-slim
              registry.gitlab.com/cyb3r-jak3/html5validator-docker:source-slim
            build-args: |
              BUILD_DATE=${BUILD_DATE}
              VCS_REF=${VCS_REF}

        - name: Source Alpine
          uses: docker/build-push-action@v2.5.0
          with:
            platforms: linux/amd64,linux/arm64,linux/arm
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache
            push: true
            file: Dockerfiles/Source/Source-alpine.DockerFile
            tags: |
              cyb3rjak3/html5validator:source-alpine
              cyb3rjak3/html5validator:source
              ghcr.io/cyb3r-jak3/html5validator:source
              ghcr.io/cyb3r-jak3/html5validator:source-alpine
              registry.gitlab.com/cyb3r-jak3/html5validator-docker:source
              registry.gitlab.com/cyb3r-jak3/html5validator-docker:source-alpine
            build-args: |
              BUILD_DATE=${BUILD_DATE}
              VCS_REF=${VCS_REF}