name: Test Build

on:
    push:
      branches-ignore:
        - master
  
jobs:
Source:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Source Docker
    run: |
        docker build --file Source.DockerFile --tag cyb3rjak3/html5validator:source --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .
Pypi:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Build PyPi Docker
    run: |
    docker build --file PyPi.DockerFile --tag cyb3rjak3/html5validator:pypi  --tag cyb3rjak3/html5validator:latest --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .
Experimental:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Experimental Docker
    run: |
        docker build --file Experimental.DockerFile --tag cyb3rjak3/html5validator:experimental --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .