name: Test Build

on: 
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '**'
    paths:
      - Dockerfiles/**
      - .github/workflows/test_build.yml
      - docker-bake.hcl
  
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: ["source", "pypi", "experimental"]
        buildArch: ["slim", "alpine"]
    steps:

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=false
          images: cyb3rjak3/html5validator,ghcr.io/cyb3r-jak3/html5validator,registry.gitlab.com/cyb3r-jak3/html5validator-docker
          labels: |
            org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/html5validator-docker.git
            maintainer=Cyb3r Jak3 jake@jwhite.network
            org.opencontainers.image.vendor=cyb3rjak3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.0  

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ matrix.buildType }}-${{ matrix.buildArch }}-${{ github.sha }}
          restore-keys: buildx-${{ matrix.buildType }}-${{ matrix.buildArch }}

      - uses: actions/checkout@v2.3.4

      - name: Build Bake ${{ matrix.buildType }}-${{ matrix.buildArch }}
        uses: docker/bake-action@v1.5.0
        with:
          files: |
            ${{ steps.meta.outputs.bake-file }}
            ./docker-bake.hcl
          targets: ${{ matrix.buildType }}-${{ matrix.buildArch }}
          push: false
          load: true
          set: |
            *.cache-from=type=local,src=/tmp/.buildx-cache
            *.cache-to=type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Run ${{ matrix.buildType }}-${{ matrix.buildArch }}
        run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:${{ matrix.buildType }}-${{ matrix.buildArch }} html5validator --root /tests/ --log DEBUG

      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache