name: Test Build

on: 
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '**'
    paths:
      - Dockerfiles/**
      - .github/workflows/test_build.yml
      - docker-bake.hcl
  
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: ["source", "pypi"]
        buildArch: ["slim", "alpine"]
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Bake ${{ matrix.buildType }}-${{ matrix.buildArch }}
        uses: docker/bake-action@v5
        with:
          files: ./docker-bake.hcl
          targets: ${{ matrix.buildType }}-${{ matrix.buildArch }}
          push: false
          load: true
          no-cache: true
        env:
          DOCKER_BUILD_SUMMARY: false

      - name: Run ${{ matrix.buildType }}-${{ matrix.buildArch }}
        run: |
          docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:${{ matrix.buildType }}-${{ matrix.buildArch }} html5validator --root /tests/ --log DEBUG
          docker run --rm -i cyb3rjak3/html5validator:${{ matrix.buildType }}-${{ matrix.buildArch }} html5validator --check-hash