name: Test Build

on: 
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '**'
    paths:
      - Dockerfiles/**
      - .github/workflows/test_build.yml
      - docker-bake.hcl
  
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: ["source", "pypi"]
        buildArch: ["slim", "alpine"]
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Bake ${{ matrix.buildType }}-${{ matrix.buildArch }}
        uses: docker/bake-action@v5
        with:
          files: ./docker-bake.hcl
          targets: ${{ matrix.buildType }}-${{ matrix.buildArch }}
          push: false
          load: true
          set: |
            *.cache-from=type=gha,scope=buildx-${{matrix.buildType}}-${{matrix.buildArch}}
            *.cache-to=type=gha,mode=max,scope=buildx-${{matrix.buildType}}-${{matrix.buildArch}}
        env:
          DOCKER_BUILD_SUMMARY: false

      - name: Run ${{ matrix.buildType }}-${{ matrix.buildArch }}
        run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:${{ matrix.buildType }}-${{ matrix.buildArch }} html5validator --root /tests/ --log DEBUG
