name: Test Build

on: 
  push:
    paths:
      - Dockerfiles/**
      - .github/workflows/test_build.yml
  
jobs:
  MatrixRun:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildType: ["Source", "PyPi", "Experimental"]
        buildArch: ["slim", "alpine"]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Build ${{ matrix.buildType }}-${{ matrix.buildArch }}
        run: docker build --file Dockerfiles/${{ matrix.buildType }}/${{ matrix.buildArch }}.Dockerfile --tag ${{ matrix.buildType }}:${{ matrix.buildArch }} .

      - name: Run Source-Alpine Docker
        run: docker run --rm -i -v $(pwd)/tests:/tests/ ${{ matrix.buildType }}:${{ matrix.buildArch }} html5validator --root /tests/valid --log DEBUG

    # Source:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - uses: actions/checkout@v2.3.4

    #     - name: Build Source Docker
    #       run: docker build --file Dockerfiles/Source/slim.Dockerfile --tag cyb3rjak3/html5validator:source --tag cyb3rjak3/html5validator:source --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .

    #     - name: Run Source Docker
    #       run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:source html5validator --root /tests/valid --log DEBUG

    # Source-Alpine:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - uses: actions/checkout@v2.3.4

    #     - name: Build Source-Alpine Docker
    #       run: docker build --file Dockerfiles/Source/alpine.Dockerfile --tag cyb3rjak3/html5validator:source-alpine --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .
  
    #     - name: Run Source-Alpine Docker
    #       run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:source-alpine html5validator --root /tests/valid --log DEBUG

    # Pypi:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - uses: actions/checkout@v2.3.4

    #     - name: Build PyPi Docker
    #       run: docker build --file Dockerfiles/PyPi/slim.Dockerfile --tag cyb3rjak3/html5validator:pypi .

    #     - name: Run PyPi Docker
    #       run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:pypi html5validator --root /tests/valid --log DEBUG
    
    # Pypi-Alpine:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - uses: actions/checkout@v2.3.4

    #     - name: Build PyPi-Alpine Docker
    #       run: docker build --file Dockerfiles/PyPi/alpine.Dockerfile --tag cyb3rjak3/html5validator:pypi-alpine .

    #     - name: Run PyPi-Alpine Docker
    #       run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:pypi-alpine html5validator --root /tests/valid --log DEBUG

    # Experimental:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - uses: actions/checkout@v2.3.4

    #     - name: Build Experimental Docker
    #       run: docker build --file Dockerfiles/Experimental/slim.Dockerfile --tag cyb3rjak3/html5validator:experimental .

    #     - name: Run Experimental Docker
    #       run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:experimental html5validator --root /tests/valid --log DEBUG

    # Experimental-Alpine:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - uses: actions/checkout@v2.3.4

    #     - name: Build Experimental-Alpine Docker
    #       run: docker build --file Dockerfiles/Experimental/alpine.Dockerfile --tag cyb3rjak3/html5validator:experimental-alpine .

    #     - name: Run Experimental-Alpine Docker
    #       run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:experimental-alpine html5validator --root /tests/valid --log DEBUG
