name: Test Build

on: 
  push:
    paths:
      - dockerfiles/**
      - .github/workflows/test_build.yml
  
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: ["source", "pypi", "experimental"]
        buildArch: ["slim", "alpine"]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Build ${{ matrix.buildType }}-${{ matrix.buildArch }}
        uses: docker/bake-action@v1.4.2
        with:
          files: |
            ./docker-bake.hcl
          targets: ${{ matrix.buildType }}-${{ matrix.buildArch }}
          push: false
          load: true

      - name: Run ${{ matrix.buildType }}-${{ matrix.buildArch }}
        run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/${{ matrix.buildType }}:${{ matrix.buildArch }} html5validator --root /tests/valid --log DEBUG
