name: Test Build

on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - Dockerfiles/**
      - .github/workflows/test_build.yml
      - docker-bake.hcl
  
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: ["source", "pypi", "experimental"]
        buildArch: ["slim", "alpine"]
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0  

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ matrix.buildType }}-${{ matrix.buildArch }}-${{ github.sha }}
          restore-keys: buildx-${{ matrix.buildType }}-${{ matrix.buildArch }}

      - uses: actions/checkout@v2.3.4

      - name: Build Bake ${{ matrix.buildType }}-${{ matrix.buildArch }}
        uses: docker/bake-action@v1.4.2
        with:
          files: |
            ./docker-bake.hcl
          targets: ${{ matrix.buildType }}-${{ matrix.buildArch }}
          push: false
          load: true

      - name: Run ${{ matrix.buildType }}-${{ matrix.buildArch }}
        run: docker run --rm -i -v $(pwd)/tests:/tests/ cyb3rjak3/html5validator:${{ matrix.buildType }}-${{ matrix.buildArch }} html5validator --root /tests/valid --log DEBUG

      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache